# Generated by Django 4.0.4 on 2022-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_dailyvitals_monthly_report_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvitals',
            name='monthly_report',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images/'),
        ),
    ]
